'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property Setting_InsertCoinButton() As Boolean
            Get
                Return CType(Me("Setting_InsertCoinButton"),Boolean)
            End Get
            Set
                Me("Setting_InsertCoinButton") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property Setting_InsertCoin_Waiting_time() As Integer
            Get
                Return CType(Me("Setting_InsertCoin_Waiting_time"),Integer)
            End Get
            Set
                Me("Setting_InsertCoin_Waiting_time") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property Settings_Rates() As String
            Get
                Return CType(Me("Settings_Rates"),String)
            End Get
            Set
                Me("Settings_Rates") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property Settings_Rates_Value() As String
            Get
                Return CType(Me("Settings_Rates_Value"),String)
            End Get
            Set
                Me("Settings_Rates_Value") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property Settings_Number_of_rates() As Integer
            Get
                Return CType(Me("Settings_Number_of_rates"),Integer)
            End Get
            Set
                Me("Settings_Number_of_rates") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property RunAtStartUp() As Boolean
            Get
                Return CType(Me("RunAtStartUp"),Boolean)
            End Get
            Set
                Me("RunAtStartUp") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DisableTaskMngr() As Boolean
            Get
                Return CType(Me("DisableTaskMngr"),Boolean)
            End Get
            Set
                Me("DisableTaskMngr") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property AutoShutdown() As Boolean
            Get
                Return CType(Me("AutoShutdown"),Boolean)
            End Get
            Set
                Me("AutoShutdown") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property AutoShutdownTime() As Integer
            Get
                Return CType(Me("AutoShutdownTime"),Integer)
            End Get
            Set
                Me("AutoShutdownTime") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property TimesUpReminder() As Boolean
            Get
                Return CType(Me("TimesUpReminder"),Boolean)
            End Get
            Set
                Me("TimesUpReminder") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public Property TimesUpWarningTime() As Integer
            Get
                Return CType(Me("TimesUpWarningTime"),Integer)
            End Get
            Set
                Me("TimesUpWarningTime") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property Terminator() As Boolean
            Get
                Return CType(Me("Terminator"),Boolean)
            End Get
            Set
                Me("Terminator") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property TerminatorExempt() As String
            Get
                Return CType(Me("TerminatorExempt"),String)
            End Get
            Set
                Me("TerminatorExempt") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("COM3")>  _
        Public Property RegisteredPort() As String
            Get
                Return CType(Me("RegisteredPort"),String)
            End Get
            Set
                Me("RegisteredPort") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("123456")>  _
        Public Property Access() As String
            Get
                Return CType(Me("Access"),String)
            End Get
            Set
                Me("Access") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property Coin_Total_One() As Integer
            Get
                Return CType(Me("Coin_Total_One"),Integer)
            End Get
            Set
                Me("Coin_Total_One") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property Coin_Total_Five() As Integer
            Get
                Return CType(Me("Coin_Total_Five"),Integer)
            End Get
            Set
                Me("Coin_Total_Five") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property Coin_Total_Ten() As Integer
            Get
                Return CType(Me("Coin_Total_Ten"),Integer)
            End Get
            Set
                Me("Coin_Total_Ten") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Settings_Rates_Name() As String
            Get
                Return CType(Me("Settings_Rates_Name"),String)
            End Get
            Set
                Me("Settings_Rates_Name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Setting_Rates_Note() As String
            Get
                Return CType(Me("Setting_Rates_Note"),String)
            End Get
            Set
                Me("Setting_Rates_Note") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("YourKing")>  _
        Public Property Setting_PC_Name() As String
            Get
                Return CType(Me("Setting_PC_Name"),String)
            End Get
            Set
                Me("Setting_PC_Name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("23")>  _
        Public Property Setting_PC_Number() As Integer
            Get
                Return CType(Me("Setting_PC_Number"),Integer)
            End Get
            Set
                Me("Setting_PC_Number") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://marketplace.canva.com/EAE-rfspHQM/1/0/1600w/canva-blue-and-purple-cyberpu"& _ 
            "nk-game-zone-desktop-background-QUVVB5lzUWo.jpg")>  _
        Public Property Setting_Banner_Path() As String
            Get
                Return CType(Me("Setting_Banner_Path"),String)
            End Get
            Set
                Me("Setting_Banner_Path") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Setting_Banner_Text() As String
            Get
                Return CType(Me("Setting_Banner_Text"),String)
            End Get
            Set
                Me("Setting_Banner_Text") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Setting_Banner_Text_Enabler() As Boolean
            Get
                Return CType(Me("Setting_Banner_Text_Enabler"),Boolean)
            End Get
            Set
                Me("Setting_Banner_Text_Enabler") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property Setting_Enable_Login_Btn() As Boolean
            Get
                Return CType(Me("Setting_Enable_Login_Btn"),Boolean)
            End Get
            Set
                Me("Setting_Enable_Login_Btn") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.CoinBoX3.My.MySettings
            Get
                Return Global.CoinBoX3.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
